# Generated by Django 3.2.8 on 2024-02-04 20:18

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ProductOwnCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('state_where_available', models.CharField(max_length=30)),
                ('lga_wheree_available', models.CharField(max_length=30)),
                ('company_selling_contact', models.CharField(max_length=255)),
                ('company_alt_phonenumber', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'productowncompanies',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=255)),
                ('name_of_manufaturer', models.CharField(max_length=255)),
                ('Country_of_manufature', django_countries.fields.CountryField(max_length=2)),
                ('year_of_production', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
                ('image', models.ImageField(default='Images/default.jpg', upload_to='shop/products/')),
                ('image2', models.ImageField(blank=True, upload_to='shop/products/')),
                ('image3', models.ImageField(blank=True, upload_to='shop/products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('puchase_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.category')),
                ('own_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_creator', to='shop.productowncompany')),
            ],
            options={
                'verbose_name_plural': 'products',
                'ordering': ('-created',),
            },
        ),
    ]
