# Generated by Django 3.2.8 on 2023-11-22 10:09

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('subject_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'serviceCategories',
            },
        ),
        migrations.CreateModel(
            name='SlideShowM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_name', models.CharField(max_length=255)),
                ('slides1', models.ImageField(blank=True, upload_to='Images/slideDisplay/')),
                ('slides2', models.ImageField(blank=True, upload_to='Images/slideDisplay/')),
                ('slides3', models.ImageField(blank=True, upload_to='Images/slideDisplay/')),
                ('Policy', models.TextField(blank=True)),
                ('about_us', models.TextField(blank=True)),
                ('terms_condtions', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'slideshowms',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
                ('description3', models.TextField(blank=True)),
                ('description4', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('icon', models.ImageField(default='Images/default.jpg', upload_to='Images/services/icon/')),
                ('image', models.ImageField(default='Images/default.jpg', upload_to='Images/services')),
                ('is_active', models.BooleanField(default=True)),
                ('sercategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='mainpage.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ImageField(blank=True, upload_to='Images/home_image/')),
                ('disciption', models.TextField(blank=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepageService', to='mainpage.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'homeimages',
            },
        ),
    ]
