# Generated by Django 3.2.8 on 2023-11-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateField()),
                ('hourly', models.TimeField()),
                ('voltage', models.FloatField()),
                ('currents', models.FloatField()),
                ('power', models.FloatField()),
                ('temp', models.FloatField()),
                ('intensity', models.FloatField()),
            ],
            options={
                'get_latest_by': ['days', 'hourly', 'voltage', 'currents', 'power', 'temp', 'intensity'],
            },
        ),
    ]
